# This workflow runs full unit tests on a matrix of OS and NodeJS combinations.

name: CI (full)

on:
  # Trigger the workflow on push or pull request,
  # but only for the specified branches
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 16
          - 14
          - 12
        os:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'
    name: 'Node ${{ matrix.node }} (${{ matrix.os }})'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
